<hr>

# Set up


<hr>

In [1]:
# Manually adding the parent directory to Root of the project
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))



#Importing python functions for integration to snowflake and other utility functions
from py_utils import snowflake_sql, nb_html_export, nb_html_slide_export,  utils
# OR import each function inside each module in py_utils package
from py_utils import convert_notebook_to_html_string, write_notebook_to_html, convert_notebook_to_slides_html, write_notebook_to_html_slide, create_snowflake_sql_engine, load_data_try_parquet_first, calculate_standardised_rates, calculate_axis_lim, get_fiscal_year

# load dataframe packages
import pandas as pd
import polars as pl

# load statistical automation package
#import ph_inequalities_statistical_comparison as phsc

# set capacity to see entire dataframe

# show more (or all) columns
pl.Config.set_tbl_cols(-1)      # -1 = no column limit [web:10][web:12]

# show more (or all) rows
pl.Config.set_tbl_rows(-1)      # -1 = no row limit [web:7][web:12]

# optional: avoid truncating long strings
pl.Config.set_fmt_str_lengths(200)  # or a larger value [web:1][web:12]

polars.config.Config

<hr>

# Query


<hr>

In [2]:
# Make sure to setup your connections.toml file before running this

# This creates the Snowflake engine that will be used to run any query on snowflake
SNOWFLAKE_ENGINE = create_snowflake_sql_engine('prd')

# This is how you load the data once SNOWFLAKE ENGINE is up.
df = load_data_try_parquet_first(SNOWFLAKE_ENGINE, parquet_file_name='Data/data.parquet', sql_path='../SQL/query.sql')

df = pl.from_pandas(df)

Initiating login request with your identity provider. Press CTRL+C to abort and try again...
Going to open: https://login.microsoftonline.com/f789227e-d70c-4029-b108-98ba67202f84/saml2?SAMLRequest=lZJRb9sgGEX%2FisWebYOXJTFKUqX1qnlLW6tJO6lvxOCEFYPLh%2BP034%2FYjdQ9tNLeLHwuHLjf7OJYq%2BAgLEij54hEGAVCl4ZLvZujh811OEUBOKY5U0aLOXoVgC4WM2C1auiydXt9L15aAS7wG2mg%2FY85aq2mhoEEqlktgLqSrpc3K5pEmDbWOFMahd5FPk8wAGGdNzxHOEivt3euoXHcdV3UfY2M3cUJxjjGaeypE%2FLlzB%2F9nT7gSYxHJ94THi%2Fe3C6lHp7gM63tAAH9sdkUYXG33qBgeVa9MhraWti1sAdZiof71SAA3kCWwJlj%2B3YbNpZHoE1XKfYsSlM3rfNbRv4rrgSPldlJf%2Bs8m6PmWfKJ%2Bv1rqrZ38HSAUeGEKf5kj7cVP2YvHSbHrBlX33PQq8ufeYmCx3OtyanWHKAVuT6V6fwSTsYhwSFJNoRQ8o2SUZTi9AkFmS9Taub65Nm494hqWVoDpnJGK6nFYDmZpkkyESGf4DIc4SQNtwRPw3S6ZeOJP6aajuJTxQkaxob2InbxX48xi99H38bv1jeSZ4VRsnwNro2tmfu4MBKRfkXysOpRKmom1ZJzKwB8cUqZ7soK5vyUO9sKFC%2BGU%2F%2Bd88Vf&RelayState=ver%3A3-hint%3A468572346519558-ETMsDgAAAaEv0u1dABRBRVMvQ0JDL1BLQ1M1UGFkZGluZwEAABAAEKWiafJq5LSNQZvKdkFO6xsAAACgOzHcWXDamDU3Nx%2BE6uXM0ujeF8z%2B3UTYaWpUCwvawT4jqWIk2wQshHzAAt%2FygCMvW9kIo9JJZhPW%2FxiCwDzqcIDXPrFMaacd7NZUW0CHR3OdmV7y4bDUX9SyYC2TGnJ0jtkn%2FRYTn51pUvlb0hqvHek0%2Bw8tso60A01miEPwWtYR8H6rF3DbfGE4J4J87If4jZlgeKc60XGzP2JuXnoExwAUTw%2Bouvcq1jRoQMeG523JcaWM5DI%3D to authenticate...
A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings.

quick overview of data

In [3]:
df.describe()

shape: (9, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ sta ┆ Pat ┆ OnW ┆ Is1 ┆ Is5 ┆ Age ┆ Gen ┆ Eth ┆ Gen ┆ Gen ┆ Gen ┆ Locati ┆ Locat ┆ Core2 ┆ C20in │
│ tis ┆ ien ┆ ait ┆ 8We ┆ 2We ┆ --- ┆ der ┆ nic ┆ era ┆ era ┆ era ┆ onLSOA ┆ ionIM ┆ 0Cate ┆ dicat │
│ tic ┆ tPs ┆ Lis ┆ eks ┆ eks ┆ f64 ┆ --- ┆ ity ┆ lPr ┆ lPr ┆ lPr ┆ Code20 ┆ DDeci ┆ goryL ┆ or    │
│ --- ┆ eud ┆ t   ┆ --- ┆ --- ┆     ┆ str ┆ Cod ┆ act ┆ act ┆ act ┆ 21     ┆ le    ┆ ist   ┆ ---   │
│ str ┆ ony ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆ e   ┆ ice ┆ ice ┆ ice ┆ ---    ┆ ---   ┆ ---   ┆ str   │
│     ┆ m   ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ Cod ┆ Pla ┆ Pla ┆ str    ┆ f64   ┆ str   ┆       │
│     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ str ┆ e   ┆ ceC ┆ ceN ┆        ┆       ┆       ┆       │
│     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ ode ┆ ame ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ cou ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169 ┆ 169808 ┆ 16926 ┆ 16980 ┆ 16980 │
│ nt  ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆ 808 ┆        ┆ 9.0   ┆ 8     ┆ 8     │
│     ┆     ┆ .0  ┆ .0  ┆ .0  ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ nul ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0      ┆ 539.0 ┆ 0     ┆ 0     │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ mea ┆ nul ┆ 1.0 ┆ 0.4 ┆ 0.0 ┆ 53. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ 5.466 ┆ null  ┆ null  │
│ n   ┆ l   ┆     ┆ 119 ┆ 230 ┆ 856 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆ 654   ┆       ┆       │
│     ┆     ┆     ┆ 18  ┆ 08  ┆ 391 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ std ┆ nul ┆ 0.0 ┆ 0.4 ┆ 0.1 ┆ 23. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ 2.383 ┆ null  ┆ null  │
│     ┆ l   ┆     ┆ 921 ┆ 499 ┆ 300 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆ 945   ┆       ┆       │
│     ┆     ┆     ┆ 82  ┆ 3   ┆ 817 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ min ┆ 000 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ Fem ┆ *   ┆ D82 ┆ 06L ┆ Gre ┆ *      ┆ 1.0   ┆ ASTHM ┆ C20   │
│     ┆ 01F ┆     ┆     ┆     ┆     ┆ ale ┆     ┆ 001 ┆     ┆ at  ┆        ┆       ┆ A     ┆       │
│     ┆ E58 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Yar ┆        ┆       ┆       ┆       │
│     ┆ 1FD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mou ┆        ┆       ┆       ┆       │
│     ┆ F65 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆        ┆       ┆       ┆       │
│     ┆ B28 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ and ┆        ┆       ┆       ┆       │
│     ┆ C98 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Wav ┆        ┆       ┆       ┆       │
│     ┆ F26 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ene ┆        ┆       ┆       ┆       │
│     ┆ F5A ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆        ┆       ┆       ┆       │
│     ┆ 3E2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 9F6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ DAC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 487 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ D84 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ E11 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ F4F ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ C18 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 72C ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 4FE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ C68 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ D3D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ C   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 25% ┆ nul ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 37. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ 4.0   ┆ null  ┆ null  │
│     ┆ l   ┆     ┆     ┆     ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 50% ┆ nul ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 58. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ 5.0   ┆ null  ┆ null  │
│     ┆ l   ┆     ┆     ┆     ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 75% ┆ nul ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 73. ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ 7.0   ┆ null  ┆ null  │
│     ┆ l   ┆     ┆     ┆     ┆ 0   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ max ┆ FFF ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 108 ┆ Not ┆ Z   ┆ Y06 ┆ 07K ┆ Wes ┆ W01002 ┆ 10.0  ┆ VET   ┆ Not   │
│     ┆ FFB ┆     ┆     ┆     ┆ .0  ┆ Rec ┆     ┆ 275 ┆     ┆ t   ┆ 002    ┆       ┆       ┆ C20   │
│     ┆ C30 ┆     ┆     ┆     ┆     ┆ ord ┆     ┆     ┆     ┆ Suf ┆        ┆       ┆       ┆       │
│     ┆ EE6 ┆     ┆     ┆     ┆     ┆ ed  ┆     ┆     ┆     ┆ fol ┆        ┆       ┆       ┆       │
│     ┆ B57 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆        ┆       ┆       ┆       │
│     ┆ DD6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ D5B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 3D6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 910 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 83B ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 549 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ DB6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 8C4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ A2D ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ B53 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ BDC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 4DC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 4DC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 717 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 597 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 8A7 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

<hr>

# Proof-Of-Concept: patients waiting 18 weeks or less


<hr>

In [4]:
import ph_inequalities_statistical_comparison as phsc

##  C20 vs not: overall

In [5]:
automated_output = phsc.crude_proportion_df(
    df,
    event_col= "Is18Weeks",
    inequalities_cols= ["C20indicator"]
)

automated_output

shape: (3, 10)
┌──────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────┬─────────┐
│ C20indic ┆ events  ┆ n       ┆ proport ┆ lower   ┆ upper   ┆ confide ┆ method  ┆ notes ┆ signifi │
│ ator     ┆ ---     ┆ ---     ┆ ion     ┆ ---     ┆ ---     ┆ nce     ┆ ---     ┆ ---   ┆ cance   │
│ ---      ┆ f64     ┆ f64     ┆ ---     ┆ f64     ┆ f64     ┆ ---     ┆ str     ┆ str   ┆ ---     │
│ str      ┆         ┆         ┆ f64     ┆         ┆         ┆ f64     ┆         ┆       ┆ str     │
╞══════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═══════╪═════════╡
│ C20      ┆ 9431.0  ┆ 22032.0 ┆ 0.42805 ┆ 0.42153 ┆ 0.43460 ┆ 0.95    ┆ Wilson  ┆       ┆ Higher  │
│          ┆         ┆         ┆ 9       ┆ 9       ┆ 5       ┆         ┆ score   ┆       ┆         │
│ Not C20  ┆ 60516.0 ┆ 147776. ┆ 0.40951 ┆ 0.40700 ┆ 0.41202 ┆ 0.95    ┆ Wilson  ┆       ┆ Not sig │
│          ┆         ┆ 0       ┆ 2       ┆ 7       ┆ 1       ┆         ┆ score   ┆       ┆ nifican │
│          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆       ┆ t       │
│ All      ┆ 69947.0 ┆ 169808. ┆ 0.41191 ┆ 0.40957 ┆ 0.41426 ┆ 0.95    ┆ Wilson  ┆       ┆ Referen │
│          ┆         ┆ 0       ┆ 8       ┆ 9       ┆ 1       ┆         ┆ score   ┆       ┆ ce      │
└──────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────┴─────────┘

# C20 crossed with Gender: inequalities lens' include overalls

In [6]:
automated_output = phsc.crude_proportion_df(
    df,
    event_col= "Is18Weeks",
    inequalities_cols= ["C20indicator", "Gender"]
)

# suppressing information for public repo

(
    automated_output
    .with_columns(
        pl.when(pl.col("n") < 5).then(None).otherwise(pl.col("n")).alias("n"),
        pl.when(pl.col("events") < 5).then(None).otherwise(pl.col("events")).alias("events")
    )
).head(100)

shape: (12, 11)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ C20ind ┆ Gender ┆ events ┆ n      ┆ propor ┆ lower  ┆ upper  ┆ confid ┆ method ┆ notes  ┆ signif │
│ icator ┆ ---    ┆ ---    ┆ ---    ┆ tion   ┆ ---    ┆ ---    ┆ ence   ┆ ---    ┆ ---    ┆ icance │
│ ---    ┆ str    ┆ f64    ┆ f64    ┆ ---    ┆ f64    ┆ f64    ┆ ---    ┆ str    ┆ str    ┆ ---    │
│ str    ┆        ┆        ┆        ┆ f64    ┆        ┆        ┆ f64    ┆        ┆        ┆ str    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ C20    ┆ Female ┆ 5472.0 ┆ 12688. ┆ 0.4312 ┆ 0.4226 ┆ 0.4399 ┆ 0.95   ┆ Wilson ┆        ┆ Higher │
│        ┆        ┆        ┆ 0      ┆ 74     ┆ 78     ┆ 11     ┆        ┆ score  ┆        ┆        │
│ C20    ┆ Male   ┆ 3958.0 ┆ 9341.0 ┆ 0.4237 ┆ 0.4137 ┆ 0.4337 ┆ 0.95   ┆ Wilson ┆        ┆ Higher │
│        ┆        ┆        ┆        ┆ 23     ┆ 36     ┆ 74     ┆        ┆ score  ┆        ┆        │
│ C20    ┆ Not    ┆ null   ┆ null   ┆ 0.3333 ┆ 0.0614 ┆ 0.7923 ┆ 0.95   ┆ Wilson ┆ Low    ┆ Not    │
│        ┆ Record ┆        ┆        ┆ 33     ┆ 92     ┆ 4      ┆        ┆ score  ┆ event  ┆ signif │
│        ┆ ed     ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ count  ┆ icant  │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<10)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - must ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ flag   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ as uns ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ table  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ or sup ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ press  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ in     ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ visual ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ output ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ s. |   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ Low    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ non-ev ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ ent    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ count  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<10)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - must ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ flag   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ as uns ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ table  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ or sup ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ press  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ in     ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ visual ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ output ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ s. |   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ Low    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ sample ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ size   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<40)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - flag ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ the    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ propo… ┆        │
│ Not    ┆ Female ┆ 34342. ┆ 83416. ┆ 0.4116 ┆ 0.4083 ┆ 0.4150 ┆ 0.95   ┆ Wilson ┆        ┆ Not    │
│ C20    ┆        ┆ 0      ┆ 0      ┆ 96     ┆ 6      ┆ 39     ┆        ┆ score  ┆        ┆ signif │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ icant  │
│ Not    ┆ Male   ┆ 26165. ┆ 64338. ┆ 0.4066 ┆ 0.4028 ┆ 0.4104 ┆ 0.95   ┆ Wilson ┆        ┆ Lower  │
│ C20    ┆        ┆ 0      ┆ 0      ┆ 8      ┆ 9      ┆ 81     ┆        ┆ score  ┆        ┆        │
│ Not    ┆ Not    ┆ 9.0    ┆ 22.0   ┆ 0.4090 ┆ 0.2325 ┆ 0.6126 ┆ 0.95   ┆ Wilson ┆ Low    ┆ Not    │
│ C20    ┆ Record ┆        ┆        ┆ 91     ┆ 58     ┆ 52     ┆        ┆ score  ┆ event  ┆ signif │
│        ┆ ed     ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ count  ┆ icant  │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<10)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - must ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ flag   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ as uns ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ table  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ or sup ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ press  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ in     ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ visual ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ output ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ s. |   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ Low    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ sample ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ size   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<40)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - flag ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ the    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ propor ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ tion   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ as uns ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ table. ┆        │
│ C20    ┆ All    ┆ 9431.0 ┆ 22032. ┆ 0.4280 ┆ 0.4215 ┆ 0.4346 ┆ 0.95   ┆ Wilson ┆        ┆ Higher │
│        ┆        ┆        ┆ 0      ┆ 59     ┆ 39     ┆ 05     ┆        ┆ score  ┆        ┆        │
│ Not    ┆ All    ┆ 60516. ┆ 147776 ┆ 0.4095 ┆ 0.4070 ┆ 0.4120 ┆ 0.95   ┆ Wilson ┆        ┆ Not    │
│ C20    ┆        ┆ 0      ┆ .0     ┆ 12     ┆ 07     ┆ 21     ┆        ┆ score  ┆        ┆ signif │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ icant  │
│ All    ┆ Female ┆ 39814. ┆ 96104. ┆ 0.4142 ┆ 0.4111 ┆ 0.4173 ┆ 0.95   ┆ Wilson ┆        ┆ Not    │
│        ┆        ┆ 0      ┆ 0      ┆ 8      ┆ 69     ┆ 98     ┆        ┆ score  ┆        ┆ signif │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ icant  │
│ All    ┆ Male   ┆ 30123. ┆ 73679. ┆ 0.4088 ┆ 0.4052 ┆ 0.4123 ┆ 0.95   ┆ Wilson ┆        ┆ Not    │
│        ┆        ┆ 0      ┆ 0      ┆ 41     ┆ 96     ┆ 96     ┆        ┆ score  ┆        ┆ signif │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ icant  │
│ All    ┆ Not    ┆ 10.0   ┆ 25.0   ┆ 0.4    ┆ 0.2340 ┆ 0.5926 ┆ 0.95   ┆ Wilson ┆ Low    ┆ Not    │
│        ┆ Record ┆        ┆        ┆        ┆ 33     ┆ 05     ┆        ┆ score  ┆ sample ┆ signif │
│        ┆ ed     ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ size   ┆ icant  │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ (<40)  ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ - flag ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ the    ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ propor ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ tion   ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ as uns ┆        │
│        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆        ┆ table. ┆        │
│ All    ┆ All    ┆ 69947. ┆ 169808 ┆ 0.4119 ┆ 0.4095 ┆ 0.4142 ┆ 0.95   ┆ Wilson ┆        ┆ Refere │
│        ┆        ┆ 0      ┆ .0     ┆ 18     ┆ 79     ┆ 61     ┆        ┆ score  ┆        ┆ nce    │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

##  C20 vs not: organisational heirarchy for place and general practice

The code below demonstrates how, for organisations, a hierarchy can be defined (where the top level categories do not share elements of lower categories).

Critically, this is implemented so that more than one level of the heirarchy can be specified without creating a degenerate level (e.g a practice in Ipswich being crossed with Central Norfolk place)

In [7]:
automated_output = phsc.crude_proportion_df(
    df,
    event_col = "Is18Weeks",
    inequalities_cols= ["C20indicator"],
    organisational_cols={
        "org": ["GeneralPracticePlaceName", "GeneralPracticeCode"]
    }
)

# suppressing information for public repo: general practice code, event count, denominator

(
    automated_output
    .with_columns(
        pl.col("GeneralPracticeCode").hash(seed=42),
        pl.when(pl.col("n") < 5).then(None).otherwise(pl.col("n")).alias("n"),
        pl.when(pl.col("events") < 5).then(None).otherwise(pl.col("events")).alias("events")
    )
).head(100)

shape: (100, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Genera ┆ Genera ┆ C20ind ┆ event ┆ n     ┆ propo ┆ lower ┆ upper ┆ confi ┆ metho ┆ notes ┆ signi │
│ lPract ┆ lPract ┆ icator ┆ s     ┆ ---   ┆ rtion ┆ ---   ┆ ---   ┆ dence ┆ d     ┆ ---   ┆ fican │
│ icePla ┆ iceCod ┆ ---    ┆ ---   ┆ f64   ┆ ---   ┆ f64   ┆ f64   ┆ ---   ┆ ---   ┆ str   ┆ ce    │
│ ceName ┆ e      ┆ str    ┆ f64   ┆       ┆ f64   ┆       ┆       ┆ f64   ┆ str   ┆       ┆ ---   │
│ ---    ┆ ---    ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   │
│ str    ┆ u64    ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ Great  ┆ 153987 ┆ C20    ┆ 319.0 ┆ 708.0 ┆ 0.450 ┆ 0.414 ┆ 0.487 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 882128 ┆        ┆       ┆       ┆ 565   ┆ 28    ┆ 383   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 644143 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 84     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 153987 ┆ Not    ┆ 803.0 ┆ 1895. ┆ 0.423 ┆ 0.401 ┆ 0.446 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 882128 ┆ C20    ┆       ┆ 0     ┆ 747   ┆ 674   ┆ 128   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 644143 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 84     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 930270 ┆ C20    ┆ 729.0 ┆ 1681. ┆ 0.433 ┆ 0.410 ┆ 0.457 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 953692 ┆        ┆       ┆ 0     ┆ 67    ┆ 157   ┆ 486   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 571110 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 930270 ┆ Not    ┆ 674.0 ┆ 1534. ┆ 0.439 ┆ 0.414 ┆ 0.464 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 953692 ┆ C20    ┆       ┆ 0     ┆ 374   ┆ 72    ┆ 331   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 571110 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 242935 ┆ C20    ┆ 130.0 ┆ 281.0 ┆ 0.462 ┆ 0.405 ┆ 0.521 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 074943 ┆        ┆       ┆       ┆ 633   ┆ 232   ┆ 042   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 871160 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 5      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 242935 ┆ Not    ┆ 906.0 ┆ 2015. ┆ 0.449 ┆ 0.428 ┆ 0.471 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 074943 ┆ C20    ┆       ┆ 0     ┆ 628   ┆ 024   ┆ 423   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 871160 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 5      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 109335 ┆ C20    ┆ 8.0   ┆ 20.0  ┆ 0.4   ┆ 0.218 ┆ 0.613 ┆ 0.95  ┆ Wilso ┆ Low   ┆ Not   │
│ Yarmou ┆ 998692 ┆        ┆       ┆       ┆       ┆ 807   ┆ 418   ┆       ┆ n     ┆ event ┆ signi │
│ th and ┆ 711999 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆ count ┆ fican │
│ Wavene ┆ 46     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ (<10) ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ -     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ must  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ flag  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ as    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ unsta ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ble   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ or    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ suppr ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ess   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ in    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ visua ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ l out ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ puts. ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ | Low ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ sampl ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ e     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ size  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ (<40) ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ -     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ flag  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ the   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ propo ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ rtion ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ as    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ unsta ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ble.  ┆       │
│ Great  ┆ 109335 ┆ Not    ┆ 996.0 ┆ 2303. ┆ 0.432 ┆ 0.412 ┆ 0.452 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 998692 ┆ C20    ┆       ┆ 0     ┆ 479   ┆ 375   ┆ 809   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 711999 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 46     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 447654 ┆ C20    ┆ 556.0 ┆ 1221. ┆ 0.455 ┆ 0.427 ┆ 0.483 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 923134 ┆        ┆       ┆ 0     ┆ 364   ┆ 615   ┆ 394   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 946947 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 6      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 447654 ┆ Not    ┆ 206.0 ┆ 501.0 ┆ 0.411 ┆ 0.368 ┆ 0.454 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 923134 ┆ C20    ┆       ┆       ┆ 178   ┆ 926   ┆ 781   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 946947 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 6      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 170025 ┆ C20    ┆ null  ┆ null  ┆ 0.0   ┆ 0.0   ┆ 0.793 ┆ 0.95  ┆ Wilso ┆ No    ┆ Not   │
│ Yarmou ┆ 700849 ┆        ┆       ┆       ┆       ┆       ┆ 451   ┆       ┆ n     ┆ event ┆ signi │
│ th and ┆ 294187 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆ s (pr ┆ fican │
│ Wavene ┆ 89     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ oport ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ion = ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 0) -  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ must  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ eithe ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ r     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ flag  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ as a  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ bound ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ary   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ estim ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ate   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ or    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ suppr ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ess   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ in    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ visua ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ l out ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ puts. ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ | Low ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ non-e ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ vent  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ count ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ (<10) ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ -     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ must  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ flag  ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ as    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ unsta ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ble   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ or    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ suppr ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ ess   ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ in    ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ visua ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ l out ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ puts. ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ | Low ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ sampl ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ e     ┆       │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ size… ┆       │
│ Great  ┆ 170025 ┆ Not    ┆ 109.0 ┆ 240.0 ┆ 0.454 ┆ 0.392 ┆ 0.517 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 700849 ┆ C20    ┆       ┆       ┆ 167   ┆ 391   ┆ 386   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 294187 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 89     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 904205 ┆ C20    ┆ 367.0 ┆ 832.0 ┆ 0.441 ┆ 0.407 ┆ 0.475 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 573910 ┆        ┆       ┆       ┆ 106   ┆ 715   ┆ 038   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 330375 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 904205 ┆ Not    ┆ 372.0 ┆ 850.0 ┆ 0.437 ┆ 0.404 ┆ 0.471 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 573910 ┆ C20    ┆       ┆       ┆ 647   ┆ 651   ┆ 204   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 330375 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 922391 ┆ C20    ┆ 94.0  ┆ 174.0 ┆ 0.540 ┆ 0.466 ┆ 0.612 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 958896 ┆        ┆       ┆       ┆ 23    ┆ 109   ┆ 613   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 643169 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 3      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 922391 ┆ Not    ┆ 924.0 ┆ 2100. ┆ 0.44  ┆ 0.418 ┆ 0.461 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 958896 ┆ C20    ┆       ┆ 0     ┆       ┆ 898   ┆ 321   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 643169 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 3      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 562428 ┆ C20    ┆ 81.0  ┆ 179.0 ┆ 0.452 ┆ 0.381 ┆ 0.525 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 818298 ┆        ┆       ┆       ┆ 514   ┆ 359   ┆ 665   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 483587 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 562428 ┆ Not    ┆ 286.0 ┆ 705.0 ┆ 0.405 ┆ 0.370 ┆ 0.442 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 818298 ┆ C20    ┆       ┆       ┆ 674   ┆ 034   ┆ 336   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 483587 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 881924 ┆ C20    ┆ 57.0  ┆ 138.0 ┆ 0.413 ┆ 0.334 ┆ 0.496 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 704547 ┆        ┆       ┆       ┆ 043   ┆ 334   ┆ 463   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 105359 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 9      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 881924 ┆ Not    ┆ 612.0 ┆ 1300. ┆ 0.470 ┆ 0.443 ┆ 0.497 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 704547 ┆ C20    ┆       ┆ 0     ┆ 769   ┆ 762   ┆ 949   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 105359 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 9      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 257375 ┆ C20    ┆ 165.0 ┆ 365.0 ┆ 0.452 ┆ 0.401 ┆ 0.503 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 774884 ┆        ┆       ┆       ┆ 055   ┆ 76    ┆ 348   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 220817 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 9      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 257375 ┆ Not    ┆ 353.0 ┆ 769.0 ┆ 0.459 ┆ 0.424 ┆ 0.494 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 774884 ┆ C20    ┆       ┆       ┆ 038   ┆ 108   ┆ 375   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 220817 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 9      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 111601 ┆ Not    ┆ 286.0 ┆ 690.0 ┆ 0.414 ┆ 0.378 ┆ 0.451 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 492445 ┆ C20    ┆       ┆       ┆ 493   ┆ 307   ┆ 625   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 583759 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 09     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 178005 ┆ C20    ┆ 252.0 ┆ 553.0 ┆ 0.455 ┆ 0.414 ┆ 0.497 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 555050 ┆        ┆       ┆       ┆ 696   ┆ 635   ┆ 369   ┆       ┆ n     ┆       ┆ r     │
│ th and ┆ 107007 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆       │
│ Wavene ┆ 65     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 178005 ┆ Not    ┆ 263.0 ┆ 646.0 ┆ 0.407 ┆ 0.369 ┆ 0.445 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 555050 ┆ C20    ┆       ┆       ┆ 121   ┆ 892   ┆ 447   ┆       ┆ n     ┆       ┆ signi │
│ th and ┆ 107007 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ score ┆       ┆ fican │
│ Wavene ┆ 65     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │

## C20 vs not: age standardized across general practice

Again, this would be an innapropriate use, but for testing this will reveal the python outputs.

In [8]:
automated_output = phsc.directly_standardized_proportion_df(
    df = df,
    event_col= "Is18Weeks",
    strata_cols= ["Age"],
    inequalities_cols= ["C20indicator"],
    organisational_cols={
        "org": ["GeneralPracticePlaceName", "GeneralPracticeCode"]
    }
)

# suppressing information for public repo: general practice code, event count, denominator

(
    automated_output
    .with_columns(
        pl.col("GeneralPracticeCode").hash(seed=42),
        pl.when(pl.col("n") < 5).then(None).otherwise(pl.col("n")).alias("n"),
        pl.when(pl.col("events") < 5).then(None).otherwise(pl.col("events")).alias("events")
    )
).head(100)

shape: (100, 12)
┌────────┬────────┬────────┬────────┬──────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Genera ┆ Genera ┆ C20ind ┆ events ┆ n    ┆ dsp   ┆ dsp_l ┆ dsp_u ┆ confi ┆ metho ┆ notes ┆ signi │
│ lPract ┆ lPract ┆ icator ┆ ---    ┆ ---  ┆ ---   ┆ ower  ┆ pper  ┆ dence ┆ d     ┆ ---   ┆ fican │
│ icePla ┆ iceCod ┆ ---    ┆ i64    ┆ i64  ┆ f64   ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ str   ┆ ce    │
│ ceName ┆ e      ┆ str    ┆        ┆      ┆       ┆ f64   ┆ f64   ┆ f64   ┆ str   ┆       ┆ ---   │
│ ---    ┆ ---    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ str   │
│ str    ┆ u64    ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪════════╪══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ Great  ┆ 153987 ┆ C20    ┆ 319    ┆ 708  ┆ 0.446 ┆ 0.409 ┆ 0.484 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 882128 ┆        ┆        ┆      ┆ 271   ┆ 283   ┆ 719   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 644143 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 84     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 153987 ┆ Not    ┆ 803    ┆ 1895 ┆ 0.423 ┆ 0.402 ┆ 0.446 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 882128 ┆ C20    ┆        ┆      ┆ 883   ┆ 07    ┆ 307   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 644143 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 84     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 930270 ┆ C20    ┆ 729    ┆ 1681 ┆ 0.427 ┆ 0.401 ┆ 0.455 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 953692 ┆        ┆        ┆      ┆ 847   ┆ 398   ┆ 434   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 571110 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 930270 ┆ Not    ┆ 674    ┆ 1534 ┆ 0.439 ┆ 0.415 ┆ 0.464 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 953692 ┆ C20    ┆        ┆      ┆ 825   ┆ 4     ┆ 843   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 571110 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 242935 ┆ C20    ┆ 130    ┆ 281  ┆ 0.451 ┆ 0.393 ┆ 0.512 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 074943 ┆        ┆        ┆      ┆ 104   ┆ 153   ┆ 987   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 871160 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 5      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 242935 ┆ Not    ┆ 906    ┆ 2015 ┆ 0.450 ┆ 0.429 ┆ 0.472 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 074943 ┆ C20    ┆        ┆      ┆ 54    ┆ 118   ┆ 326   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 871160 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 5      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 109335 ┆ C20    ┆ 8      ┆ 20   ┆ 0.383 ┆ 0.247 ┆ 0.573 ┆ 0.95  ┆ Wilso ┆ Unrel ┆ Not   │
│ Yarmou ┆ 998692 ┆        ┆        ┆      ┆ 026   ┆ 422   ┆ 713   ┆       ┆ n-MOV ┆ iable ┆ signi │
│ th and ┆ 711999 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆ : at  ┆ fican │
│ Wavene ┆ 46     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ least ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ one   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ strat ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ um    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ has n ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ < 10  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ flag  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ as    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ unsta ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ble   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ or    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ suppr ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ess   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ in    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ visua ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ l out ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ puts  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ and   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ stron ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ gly   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ consi ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ der   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ coars ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ening ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ strat ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ a,    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ inequ ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ aliti ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ es or ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ dimen ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ sions ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ | Unr ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ eliab ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ le:   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ strat ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ um    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ non-e ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ vent  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ count ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ < 1…  ┆       │
│ Great  ┆ 109335 ┆ Not    ┆ 996    ┆ 2303 ┆ 0.435 ┆ 0.414 ┆ 0.455 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 998692 ┆ C20    ┆        ┆      ┆ 075   ┆ 7     ┆ 88    ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 711999 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 46     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 447654 ┆ C20    ┆ 556    ┆ 1221 ┆ 0.441 ┆ 0.412 ┆ 0.471 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 923134 ┆        ┆        ┆      ┆ 582   ┆ 697   ┆ 783   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 946947 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 6      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 447654 ┆ Not    ┆ 206    ┆ 501  ┆ 0.413 ┆ 0.372 ┆ 0.457 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 923134 ┆ C20    ┆        ┆      ┆ 629   ┆ 433   ┆ 295   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 946947 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 6      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 170025 ┆ C20    ┆ null   ┆ null ┆ 0.0   ┆ 0.0   ┆ 0.793 ┆ 0.95  ┆ Wilso ┆ Calcu ┆ Not   │
│ Yarmou ┆ 700849 ┆        ┆        ┆      ┆       ┆       ┆ 451   ┆       ┆ n-MOV ┆ lated ┆ signi │
│ th and ┆ 294187 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆ with  ┆ fican │
│ Wavene ┆ 89     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ missi ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ng    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ stand ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ardis ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ation ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ strat ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ a: 3  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ strat ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ a omi ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ tted, ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ repre ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ senti ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ng    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ 74.6% ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ of    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ the   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ refer ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ence  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ popul ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ation ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ; the ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ remai ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ning  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ refer ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ence  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ weigh ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ts    ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ (25.4 ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ % cov ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ erage ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ )     ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ were  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ renor ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ malis ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ ed to ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ sum   ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ to 1  ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ Stron ┆       │
│        ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆ gl…   ┆       │
│ Great  ┆ 170025 ┆ Not    ┆ 109    ┆ 240  ┆ 0.460 ┆ 0.398 ┆ 0.524 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 700849 ┆ C20    ┆        ┆      ┆ 585   ┆ 623   ┆ 726   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 294187 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 89     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 904205 ┆ C20    ┆ 367    ┆ 832  ┆ 0.430 ┆ 0.395 ┆ 0.466 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 573910 ┆        ┆        ┆      ┆ 339   ┆ 92    ┆ 588   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 330375 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 904205 ┆ Not    ┆ 372    ┆ 850  ┆ 0.439 ┆ 0.406 ┆ 0.473 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 573910 ┆ C20    ┆        ┆      ┆ 364   ┆ 756   ┆ 025   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 330375 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 922391 ┆ C20    ┆ 94     ┆ 174  ┆ 0.516 ┆ 0.447 ┆ 0.587 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 958896 ┆        ┆        ┆      ┆ 444   ┆ 025   ┆ 413   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 643169 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 3      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 922391 ┆ Not    ┆ 924    ┆ 2100 ┆ 0.440 ┆ 0.419 ┆ 0.462 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 958896 ┆ C20    ┆        ┆      ┆ 735   ┆ 622   ┆ 283   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 643169 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 3      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 562428 ┆ C20    ┆ 81     ┆ 179  ┆ 0.479 ┆ 0.404 ┆ 0.553 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 818298 ┆        ┆        ┆      ┆ 692   ┆ 498   ┆ 684   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 483587 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 562428 ┆ Not    ┆ 286    ┆ 705  ┆ 0.415 ┆ 0.379 ┆ 0.453 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 818298 ┆ C20    ┆        ┆      ┆ 793   ┆ 331   ┆ 841   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 483587 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 0      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 881924 ┆ C20    ┆ 57     ┆ 138  ┆ 0.408 ┆ 0.335 ┆ 0.491 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 704547 ┆        ┆        ┆      ┆ 447   ┆ 538   ┆ 508   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 105359 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 9      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 881924 ┆ Not    ┆ 612    ┆ 1300 ┆ 0.474 ┆ 0.447 ┆ 0.502 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 704547 ┆ C20    ┆        ┆      ┆ 688   ┆ 401   ┆ 231   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 105359 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 9      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 257375 ┆ C20    ┆ 165    ┆ 365  ┆ 0.445 ┆ 0.396 ┆ 0.497 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 774884 ┆        ┆        ┆      ┆ 832   ┆ 496   ┆ 925   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 220817 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 9      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 257375 ┆ Not    ┆ 353    ┆ 769  ┆ 0.459 ┆ 0.425 ┆ 0.495 ┆ 0.95  ┆ Wilso ┆       ┆ Highe │
│ Yarmou ┆ 774884 ┆ C20    ┆        ┆      ┆ 808   ┆ 162   ┆ 238   ┆       ┆ n-MOV ┆       ┆ r     │
│ th and ┆ 220817 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆       │
│ Wavene ┆ 9      ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ y      ┆        ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ Great  ┆ 111601 ┆ Not    ┆ 286    ┆ 690  ┆ 0.431 ┆ 0.392 ┆ 0.471 ┆ 0.95  ┆ Wilso ┆       ┆ Not   │
│ Yarmou ┆ 492445 ┆ C20    ┆        ┆      ┆ 701   ┆ 975   ┆ 648   ┆       ┆ n-MOV ┆       ┆ signi │
│ th and ┆ 583759 ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆ ER    ┆       ┆ fican │
│ Wavene ┆ 09     ┆        ┆        ┆      ┆       ┆       ┆       ┆       ┆       ┆       ┆ t     │

You will notice for certain rows, the confidence interval and dsp exactly match. This is because there is a 100% proportion